- hosts: linux
  tasks:
  - name: create multiple directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
    - /home/ansible/folder1
    - /home/ansible/folder2
    - /home/ansible/folder3
